services:
  postgres:
    image: postgres:18.1
    container_name: 'guide-postgres'
    shm_size: 128mb
    restart: on-failure:3
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=openpostgresql
      - POSTGRES_USER=guide
      - POSTGRES_DB=guide
      - PGUSER=guide
  redis:
    image: redis:8.4.0
    container_name: 'guide-redis-dev'
    shm_size: 128mb
    restart: on-failure:3
    ports:
      - "6388:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5